### ISSUE TITLE
IOS: Missing resource files

### ISSUE THREAD

**Issue by SanHoser** [CreativeSDK/phonegap-plugin-csdk-client-auth#1]
In the plugin.xml file two resource files are defined, but seemed to be missing from the git repot (see below). 

<resource-file src="src/ios/AdobeCreativeSDKFrameworks/AdobeCreativeSDKCore.framework/Versions/A/Resources/AdobeCreativeSDKCoreResources.bundle" />
        <framework src="src/ios/AdobeCreativeSDKFrameworks/AdobeCreativeSDKCore.framework" custom="true" />

When adding the ios platform to my project  (cordova platform add ios)  I end up with the following error:

Error during processing of action! Attempting to revert...
Failed to install 'phonegap-plugin-csdk-client-auth':Error: Uh oh!
cannot find "/Users/stevenlewis/dev/git/editor/plugins/phonegap-plugin-csdk-client-auth/src/ios/AdobeCreativeSDKFrameworks/AdobeCreativeSDKCore.framework/Versions/A/Resources/AdobeCreativeSDKCoreResources.bundle" ios <resource-file>
    at Object.module.exports.resource-file.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:158:48)
    at installWrapper (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
Error: Uh oh!
cannot find "/Users/stevenlewis/dev/git/editor/plugins/phonegap-plugin-csdk-client-auth/src/ios/AdobeCreativeSDKFrameworks/AdobeCreativeSDKCore.framework/Versions/A/Resources/AdobeCreativeSDKCoreResources.bundle" ios <resource-file>

**Comment by macdonst** [comment]
@SanHoser yeah, I mention that you need to get the iOS SDK and extract it to the src/ios directory in the [README](https://github.com/CreativeSDK/phonegap-plugin-csdk-client-auth#prerequisites). Once cordova-ios supports cocoapods the plan is to include the SDK as a cocoapod so you can skip this step.

Make sense?

**Comment by SanHoser** [comment]
That did the trick.   

Thx!
Steve
